// import axios from 'axios';

// const API_KEY = import.meta.env.REACT_APP_GOOGLE_TRANSLATE_API_KEY;
// const BASE_URL = 'https://translation.googleapis.com/language/translate/v2';

// export interface TranslateResponse {
//   data: {
//     translations: Array<{
//       translatedText: string;
//     }>;
//   };
// }

// // Mock translations for demo purposes when API key is not available
// const mockTranslations: Record<string, Record<string, string>> = {
//   en: {
//     'Dashboard': 'Dashboard',
//     'logout': 'Logout',
//     'Français': 'French',
//     'English': 'English',
//     'العربية': 'Arabic',
//     'Poste Smart': 'Poste Smart',
//     'deconnexion': 'logout',
//     'Tableau de bord': 'Dashboard',
//     'Utilisateurs': 'Users',
//     'Finance': 'Finance',
//     'Vente': 'Sales',
//     'distributeur': 'Distributor',
//     'Paramètre': 'Settings',
//     'Admin': 'Admin',
//     'Chargement des performances...': 'Loading performances...',
//     'Marchand': 'Merchant',
//     'Performance et transactions des marchands.': 'Merchant performance and transactions.',
//     'Ventes totales': 'Total Sales',
//     'Transactions réussies': 'Successful Transactions',
//     'En attente': 'Pending',
//     'Échouées': 'Failed',
//     'Suivi des performances': 'Performance Tracking',
//     'Nom': 'Name',
//     'Gestion des Utilisateurs': 'User Management',
//     'Profil': 'Profile',
//     'Email': 'Email',
//     'Date Inscription': 'Registration Date',
//     'Rôle': 'Role',
//     'Statut': 'Status',
//     'Actions': 'Actions',
//     'Rechercher une option': 'Search an option',
//     'Actif': 'Active',
//     'Suspendu': 'Suspended',
//     'Suspendre': 'Suspend',
//     'Activer': 'Activate',
//     'Page': 'Page',
//     'sur': 'of',
//     'utilisateurs': 'users',
//     'Précédent': 'Previous',
//     'Suivant': 'Next',
//     'admin': 'admin',
//     'user': 'user',
//     'superadmin': 'superadmin',
//     'Sous-magasin': 'Sub-store',
//     'Transactions': 'Transactions',
//     'Succès': 'Success',
//     'Total (€)': 'Total (€)',
//     'Exporter CSV': 'Export CSV',
//     'Distributeur': 'Distributor',
//     'Performance et transactions des distributeurs.': 'Distributor performance and transactions.',
//     'Commission moyenne': 'Average Commission',
//     'Stock disponible': 'Available Stock',
//     'Finance_transactions_overview': 'Financial transactions overview',
//     'total_revenue': 'Total Revenue',
//     'total_expenses': 'Total Expenses',
//     'balance': 'Balance',
//     'revenue': 'Revenue',
//     'expenses': 'Expenses',
//     'Ventes': 'Sales',
//     'Statistiques et suivi des ventes mensuelles.': 'Statistics and monthly sales tracking.',
//     'Total annuel': 'Annual Total',
//     'Meilleur mois': 'Best Month',
//     'Croissance': 'Growth',
//     'Suivi des ventes': 'Sales Tracking',
//     'Chargement des ventes...': 'Loading sales...',
//     'Module IT - Support & Gestion': 'IT Module - Support & Management',
//     'Tous': 'All',
//     'Ouvert': 'Open',
//     'En cours': 'In Progress',
//     'Résolu': 'Resolved',
//     'Chargement des tickets...': 'Loading tickets...',
//     'Erreur lors du chargement des tickets.': 'Error loading tickets.',
//     'Total Utilisateurs': 'Total Users',
//     'Nouveaux Utilisateurs (30j)': 'New Users (30d)',
//     'Volume Total (Entrant)': 'Total Volume (Incoming)',
//     'Taux de Succès (Tx)': 'Success Rate (Tx)',
//     'Détails Financiers (30j)': 'Financial Details (30d)',
//     'Revenu Estimé:': 'Estimated Revenue:',
//     'Volume Sortant:': 'Outgoing Volume:',
//     'Valeur Moyenne de Transaction:': 'Average Transaction Value:',
//     'Total Marchands:': 'Total Merchants:',
//     'Marchands Actifs:': 'Active Merchants:',
//     'Activité par Devise (30j)': 'Activity by Currency (30d)',
//     'Devise': 'Currency',
//     'Volume Entrant': 'Incoming Volume',
//     'Échecs': 'Failures',
//     'Rapport de transaction': 'Transaction Report',
//     'Chargement des statistiques...': 'Loading statistics...',
//     'Vos transactions et performances.': 'Your transactions and performances.',
//     'Mes Transactions': 'My Transactions',
//     'Produit': 'Product',
//     'Montant ($)': 'Amount ($)',
//     'Date': 'Date',
//     'Exporter Excel': 'Export Excel',
//     'Chargement du tableau de bord...': 'Loading dashboard...',
//     'Ventes Totales': 'Total Sales',
//     'Commission Moyenne': 'Average Commission',
//     'Stock Disponible': 'Available Stock',
//     'Commissions Totales Gagnées': 'Total Commissions Earned',
//     'Informations du Profil': 'Profile Information',
//     'Nom:': 'Name:',
//     'Rôle:': 'Role:',
//     'Solde du Portefeuille': 'Wallet Balance',
//     'ID Transaction': 'Transaction ID',
//     'Montant': 'Amount',
//     'Type': 'Type',
//     'Erreur lors du chargement des transactions.': 'Error loading transactions.',
//     'Aucune notification': 'No notifications',
//     'loading_transactions': 'Loading transactions',
//     'Déconnexion': 'Logout',
    
//   },
//   ar: {
//     'Dashboard': 'لوحة التحكم',
//     'logout': 'تسجيل الخروج',
//     'Français': 'الفرنسية',
//     'English': 'الإنجليزية',
//     'العربية': 'العربية',
//     'Poste Smart': 'بوست سمارت',
//     'Tableau de bord': 'لوحة التحكم',
//     'Utilisateurs': 'المستخدمون',
//     'Finance': 'المالية',
//     'Vente': 'المبيعات',
//     'distributeur': 'الموزع',
//     'Paramètre': 'الإعدادات',
//     'Admin': 'المدير',
//     'Chargement des performances...': 'جارٍ تحميل الأداء...',
//     'Marchand': 'التاجر',
//     'Performance et transactions des marchands.': 'أداء التجار والمعاملات.',
//     'Ventes totales': 'إجمالي المبيعات',
//     'Transactions réussies': 'المعاملات الناجحة',
//     'En attente': 'في الانتظار',
//     'Échouées': 'فاشلة',
//     'Suivi des performances': 'تتبع الأداء',
//     'Nom': 'الاسم',
//     'Sous-magasin': 'المتجر الفرعي',
//     'Transactions': 'المعاملات',
//     'Succès': 'النجاح',
//     'Total (€)': 'الإجمالي (€)',
//     'Exporter CSV': 'تصدير CSV',
//     'Distributeur': 'الموزع',
//     'Performance et transactions des distributeurs.': 'أداء الموزعين والمعاملات.',
//     'Commission moyenne': 'متوسط العمولة',
//     'Stock disponible': 'المخزون المتاح',
//     'Finance_transactions_overview': 'نظرة عامة على المعاملات المالية',
//     'total_revenue': 'إجمالي الإيرادات',
//     'total_expenses': 'إجمالي المصروفات',
//     'balance': 'الرصيد',
//     'revenue': 'الإيرادات',
//     'expenses': 'المصروفات',
//     'Ventes': 'المبيعات',
//     'Statistiques et suivi des ventes mensuelles.': 'إحصائيات وتتبع المبيعات الشهرية.',
//     'Total annuel': 'الإجمالي السنوي',
//     'Meilleur mois': 'أفضل شهر',
//     'Croissance': 'النمو',
//     'Suivi des ventes': 'تتبع المبيعات',
//     'Chargement des ventes...': 'تحميل المبيعات...',
//     'Module IT - Support & Gestion': 'وحدة تكنولوجيا المعلومات - الدعم والإدارة',
//     'Tous': 'الكل',
//     'Ouvert': 'مفتوح',
//     'En cours': 'قيد التنفيذ',
//     'Résolu': 'محلول',
//     'Chargement des tickets...': 'تحميل التذاكر...',
//     'Erreur lors du chargement des tickets.': 'خطأ في تحميل التذاكر.',
//     'Total Utilisateurs': 'إجمالي المستخدمين',
//     'Nouveaux Utilisateurs (30j)': 'مستخدمون جدد (30 يومًا)',
//     'Volume Total (Entrant)': 'الحجم الإجمالي (الوارد)',
//     'Taux de Succès (Tx)': 'معدل النجاح (Tx)',
//     'Détails Financiers (30j)': 'التفاصيل المالية (30 يومًا)',
//     'Revenu Estimé:': 'الإيراد المقدر:',
//     'Volume Sortant:': 'الحجم الصادر:',
//     'Valeur Moyenne de Transaction:': 'قيمة المعاملة المتوسطة:',
//     'Total Marchands:': 'إجمالي التجار:',
//     'Marchands Actifs:': 'التجار النشطون:',
//     'Activité par Devise (30j)': 'النشاط حسب العملة (30 يومًا)',
//     'Devise': 'العملة',
//     'Volume Entrant': 'الحجم الوارد',
//     'Échecs': 'الفشل',
//     'Rapport de transaction': 'تقرير المعاملة',
//     'Chargement des statistiques...': 'تحميل الإحصائيات...',
//     'Vos transactions et performances.': 'معاملاتك وأدائك.',
//     'Mes Transactions': 'معاملاتي',
//     'Produit': 'المنتج',
//     'Montant ($)': 'المبلغ ($)',
//     'Date': 'التاريخ',
//     'Exporter Excel': 'تصدير Excel',
//     'Chargement du tableau de bord...': 'تحميل لوحة التحكم...',
//     'Ventes Totales': 'إجمالي المبيعات',
//     'Commission Moyenne': 'متوسط العمولة',
//     'Stock Disponible': 'المخزون المتاح',
//     'Commissions Totales Gagnées': 'إجمالي العمولات المكتسبة',
//     'Informations du Profil': 'معلومات الملف الشخصي',
//     'Nom:': 'الاسم:',
//     'Rôle:': 'الدور:',
//     'Solde du Portefeuille': 'رصيد المحفظة',
//     'ID Transaction': 'معرف المعاملة',
//     'Montant': 'المبلغ',
//     'Type': 'النوع',
//     'Erreur lors du chargement des transactions.': 'خطأ في تحميل المعاملات.',
//     'Aucune notification': 'لا توجد إشعارات',
//     'loading_transactions': 'تحميل المعاملات',
//     'Déconnexion': 'تسجيل الخروج',
//   },
// };

// export const translateText = async (
//   text: string,
//   targetLanguage: string,
//   sourceLanguage: string = 'fr'
// ): Promise<string> => {
//   if (!API_KEY) {
//     console.warn('Google Translate API key not found. Using mock translations for demo.');
//     // Return mock translation if available, otherwise original text
//     const mock = mockTranslations[targetLanguage]?.[text];
//     return mock || text;
//   }

//   try {
//     const response = await axios.post<TranslateResponse>(BASE_URL, null, {
//       params: {
//         q: text,
//         target: targetLanguage,
//         source: sourceLanguage,
//         key: API_KEY,
//       },
//     });

//     return response.data.data.translations[0].translatedText;
//   } catch (error) {
//     console.error('Translation error:', error);
//     // Fallback to mock translation or original text
//     const mock = mockTranslations[targetLanguage]?.[text];
//     return mock || text;
//   }
// };
